# Generated by Django 4.2.18 on 2025-02-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=255)),
            ],
        ),
    ]
