# Generated by Django 4.2.18 on 2025-02-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_mycustompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyCustomPermission',
        ),
    ]
