# Generated by Django 4.2.18 on 2025-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_delete_mycustompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят')], default='pending', max_length=10),
        ),
    ]
